[package]
name = "artimonist"
version = "0.6.0"
authors = ["Artimonist <artimonist@gmail.com>"]
description = "A tool for generating mnemonics based on diagrams."
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-lib/"

license = "MIT"
keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.84.0"
edition = "2021"
crate-type = ["lib"]

[features]
default = []
multilingual = []

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[dependencies]
bitcoin = "0.32.5"
# crypto libs from: https://github.com/RustCrypto
scrypt = { version = "0.11.0", default-features = false }
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
# -----------------------------------------------
thiserror = "2"
unicode-normalization = "0.1.24"

[dev-dependencies]
bitcoin = { version = "0.32.5", features = ["base64"] }
rust-crypto = "0.2" # not support wasm, because of rustc-serialize v0.3.25
