[package]
name = "artimonist"
version = "0.11.3"
authors = ["Artimonist <artimonist@gmail.com>"]
description = "A tool for generating mnemonics and wallets based on diagrams."
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/core/"

license = "MIT"
keywords = ["bitcoin", "mnemonic", "wallet"]
categories = ["cryptography"]
rust-version = "1.84"
edition = "2021"
crate-type = ["lib"]

[features]
default = []
multilingual = [] # multiple languages
testnet = [] # use testnet
serde = ["dep:serde", "dep:rmp-serde"] # generic diagram

[dependencies]
bitcoin = "0.32.5"
thiserror = "2.0.11"
# crypto libs
scrypt = { version = "0.11.0", default-features = false }
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
# optional
serde = { version = "1.0.217", features = ["derive"], optional = true }
rmp-serde = { version = "1.3.0", optional = true }

[dev-dependencies]
bitcoin = { version = "0.32.5", features = ["base64"] }
rust-crypto = "0.2" # not support wasm, because of rustc-serialize v0.3.25
