[package]
name = "artimonist"
version = "0.8.0"
authors = ["Artimonist <artimonist@gmail.com>"]
description = "A tool for generating mnemonics based on diagrams."
homepage = "https://artimonist.org/"
repository = "https://github.com/artimonist/artimonist-lib/"

license = "MIT"
keywords = ["bitcoin", "mnemonic"]
categories = ["cryptography"]
rust-version = "1.84.0"
edition = "2021"
crate-type = ["lib"]

[features]
default = []
multilingual = []

[dependencies]
bitcoin = "0.32.5"
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"] }
rmp-serde = "1.3.0"
# crypto libs
scrypt = { version = "0.11.0", default-features = false }
pbkdf2 = "0.12.2"
sha2 = "0.10.8"

aes = "0.8.4"
unicode-normalization = "0.1.24"


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[dev-dependencies]
bitcoin = { version = "0.32.5", features = ["base64"] }
rust-crypto = "0.2" # not support wasm, because of rustc-serialize v0.3.25
aes-gcm = "0.10.3"
